apiVersion: v1
kind: Secret
metadata:
  name: azure-mysql-secret
  namespace: hospital-system
  labels:
    app: hospital-backend
    database: azure-mysql
type: Opaque
data:
  DB_HOST: bXlhcHAtbXlzcWwtc2VydmVyLm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_USER: bWFub2o=
  DB_PASSWORD: Q2hhd2FrdWxhJTQwMDExMw==
  DB_NAME: aG9zcGl0YWxkYg==
